name: Test

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "docs/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run type checks
        run: npm run type-check

      - name: Run tests
        run: npm run test

      - name: Run Expo doctor
        run: npm run validate:expo:doctor

      - name: Run Expo install check
        run: npm run validate:expo:install-check
